# Generated by Django 3.1.7 on 2021-03-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='상품명')),
                ('manufacturer', models.CharField(max_length=256, verbose_name='제조사')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('price', models.IntegerField(verbose_name='단가')),
                ('shelf_life', models.DateField(blank=True, verbose_name='유통기한')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'products',
            },
        ),
    ]
